name: expenses
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  intl: ^0.18.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.18
  http: ^0.13.5
  flutter_flavor: ^3.1.1
  device_preview: ^1.1.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  mocktail: ^0.3.0
  fluttertoast: ^8.2.1
  local_auth: ^2.1.6
  local_auth_android: ^1.0.23
  local_auth_ios: ^1.1.1
  go_router: ^6.5.6
  flutter_secure_storage: ^8.0.0
  dio: ^5.1.0
  pretty_dio_logger: ^1.3.1
  auto_size_text: ^3.0.0
  jwt_decoder: ^2.0.1
  curl_logger_dio_interceptor: ^1.0.0
  flutter_easyloading: ^3.0.5
  webview_flutter: ^4.2.0
  socket_io_client: ^2.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  flutter_gen: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/waiting.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
